server:
  port: 9090
spring:
  application:
    name: gateway
eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    nonSecurePort: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId:  ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/      
 
zuul:
  routes:
    customer:
      path: /customer/**
      stripPrefix: false
    orders:
      path: /order/**
      stripPrefix: false
    product:
      path: /product/**
      stripPrefix: false
      
       
      
      
      

 